info:
  contact:
    email: support@redirection.engine
    name: API Support
  description: High-performance microservices-based URL redirection engine.
  title: Redirection Engine API
  version: "1.0"
paths: {}
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
